"""initial schema

Revision ID: 14ae106d2a45
Revises: 
Create Date: 2026-08-13 04:44:06.225850
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import app.db  # noqa: F401  (app.db.Money)
import app.models.json_type  # noqa: F401  (app.models.json_type.JSONText)


revision = '14ae106d2a45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('before_json', app.models.json_type.JSONText(), nullable=True),
    sa.Column('after_json', app.models.json_type.JSONText(), nullable=True),
    sa.Column('context_json', app.models.json_type.JSONText(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('cin', sa.String(length=30), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('bank_name', sa.String(length=160), nullable=True),
    sa.Column('bank_account_no', sa.String(length=40), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('bank_branch', sa.String(length=160), nullable=True),
    sa.Column('logo_path', sa.String(length=400), nullable=True),
    sa.Column('fy_start_month', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('place_of_supply_state_code', sa.String(length=2), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('payment_terms_default', sa.Text(), nullable=True),
    sa.Column('is_sez', sa.Boolean(), nullable=False),
    sa.Column('is_export', sa.Boolean(), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_name', ['name'], unique=False)

    op.create_table('document_series',
    sa.Column('series_key', sa.String(length=30), nullable=False),
    sa.Column('financial_year', sa.String(length=7), nullable=False),
    sa.Column('pattern', sa.String(length=120), nullable=False),
    sa.Column('next_seq', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_key', 'financial_year', name='uq_series_fy')
    )
    op.create_table('documents',
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=600), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'sha256', name='uq_documents_kind_sha')
    )
    op.create_table('extractions',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('extractor_name', sa.String(length=60), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('schema_name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('parsed_json', app.models.json_type.JSONText(), nullable=True),
    sa.Column('field_confidence_json', app.models.json_type.JSONText(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('warnings_json', app.models.json_type.JSONText(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hsn_code', sa.String(length=10), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('default_unit_price', app.db.Money(precision=18, scale=4), nullable=True),
    sa.Column('is_service', sa.Boolean(), nullable=False),
    sa.Column('spec_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_items_sku')
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('msme_registration_no', sa.String(length=40), nullable=True),
    sa.Column('payment_terms_default', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tally_export_items',
    sa.Column('export_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('remote_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('export_id', 'document_type', 'document_id', name='uq_tally_item')
    )
    op.create_table('tally_exports',
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('voucher_count', sa.Integer(), nullable=False),
    sa.Column('manifest_json', app.models.json_type.JSONText(), nullable=True),
    sa.Column('xml_path', sa.String(length=600), nullable=True),
    sa.Column('delivery', sa.String(length=20), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tally_ledger_mappings',
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('local_key', sa.String(length=120), nullable=False),
    sa.Column('tally_ledger_name', sa.String(length=200), nullable=False),
    sa.Column('tally_parent_group', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'local_key', name='uq_tally_scope_key')
    )
    op.create_table('tax_rates',
    sa.Column('hsn_code', sa.String(length=10), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('rate_percent', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('cess_percent', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_rates', schema=None) as batch_op:
        batch_op.create_index('ix_tax_rates_hsn_from', ['hsn_code', 'effective_from'], unique=False)

    op.create_table('sales_orders',
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('customer_po_number', sa.String(length=80), nullable=False),
    sa.Column('customer_po_date', sa.Date(), nullable=False),
    sa.Column('order_value', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('delivery_due_date', sa.Date(), nullable=True),
    sa.Column('delivery_location', sa.Text(), nullable=True),
    sa.Column('payment_terms_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('extraction_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.create_index('ix_sales_orders_status', ['status'], unique=False)

    op.create_table('supplier_offers',
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('offer_ref', sa.String(length=80), nullable=True),
    sa.Column('offer_date', sa.Date(), nullable=True),
    sa.Column('validity_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('payment_terms_text', sa.Text(), nullable=True),
    sa.Column('freight_terms', sa.Text(), nullable=True),
    sa.Column('warranty_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('extraction_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('number', sa.String(length=60), nullable=False),
    sa.Column('series_key', sa.String(length=30), nullable=False),
    sa.Column('financial_year', sa.String(length=7), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('sales_order_id', sa.String(length=36), nullable=True),
    sa.Column('payment_milestone_id', sa.String(length=36), nullable=True),
    sa.Column('place_of_supply_state_code', sa.String(length=2), nullable=True),
    sa.Column('is_reverse_charge', sa.Boolean(), nullable=False),
    sa.Column('is_export', sa.Boolean(), nullable=False),
    sa.Column('lut_no', sa.String(length=60), nullable=True),
    sa.Column('taxable_value', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('cgst_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('sgst_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('igst_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('cess_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('round_off', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('grand_total', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('amount_in_words', sa.String(length=400), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('template_name', sa.String(length=120), nullable=True),
    sa.Column('template_version', sa.Integer(), nullable=True),
    sa.Column('render_context_json', app.models.json_type.JSONText(), nullable=True),
    sa.Column('pdf_path', sa.String(length=600), nullable=True),
    sa.Column('docx_path', sa.String(length=600), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('irn', sa.String(length=80), nullable=True),
    sa.Column('ack_no', sa.String(length=40), nullable=True),
    sa.Column('qr_payload', sa.Text(), nullable=True),
    sa.Column('eway_bill_no', sa.String(length=30), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', name='uq_invoices_number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoices_type_date', ['doc_type', 'invoice_date'], unique=False)

    op.create_table('payment_milestones',
    sa.Column('sales_order_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('trigger_event', sa.String(length=30), nullable=False),
    sa.Column('percent', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('net_days', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proforma_invoice_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('number', sa.String(length=60), nullable=False),
    sa.Column('financial_year', sa.String(length=7), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_offer_id', sa.String(length=36), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('delivery_due_date', sa.Date(), nullable=True),
    sa.Column('delivery_location', sa.Text(), nullable=True),
    sa.Column('payment_terms_text', sa.Text(), nullable=True),
    sa.Column('freight_terms', sa.Text(), nullable=True),
    sa.Column('warranty_text', sa.Text(), nullable=True),
    sa.Column('place_of_supply_state_code', sa.String(length=2), nullable=True),
    sa.Column('is_reverse_charge', sa.Boolean(), nullable=False),
    sa.Column('taxable_value', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('cgst_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('sgst_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('igst_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('cess_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('round_off', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('grand_total', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('amount_in_words', sa.String(length=400), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('template_name', sa.String(length=120), nullable=True),
    sa.Column('template_version', sa.Integer(), nullable=True),
    sa.Column('render_context_json', app.models.json_type.JSONText(), nullable=True),
    sa.Column('docx_path', sa.String(length=600), nullable=True),
    sa.Column('pdf_path', sa.String(length=600), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['supplier_offer_id'], ['supplier_offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', name='uq_purchase_orders_number')
    )
    op.create_table('sales_order_lines',
    sa.Column('sales_order_id', sa.String(length=36), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hsn_code', sa.String(length=10), nullable=True),
    sa.Column('qty', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('unit_price', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('discount_percent', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('line_total', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_offer_lines',
    sa.Column('supplier_offer_id', sa.String(length=36), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hsn_code', sa.String(length=10), nullable=True),
    sa.Column('qty', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('quoted_unit_price', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('negotiated_unit_price', app.db.Money(precision=18, scale=4), nullable=True),
    sa.Column('discount_percent', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['supplier_offer_id'], ['supplier_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_lines',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hsn_code', sa.String(length=10), nullable=True),
    sa.Column('qty', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('unit_price', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('discount_percent', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('taxable_value', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('gst_rate_percent', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('cgst_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('sgst_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('igst_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('cess_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('line_total', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_lines',
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hsn_code', sa.String(length=10), nullable=True),
    sa.Column('qty', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('unit_price', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('discount_percent', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('taxable_value', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('gst_rate_percent', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('cgst_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('sgst_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('igst_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('cess_amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('line_total', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipts',
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('sales_order_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('amount', app.db.Money(precision=18, scale=4), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.drop_table('purchase_order_lines')
    op.drop_table('invoice_lines')
    op.drop_table('supplier_offer_lines')
    op.drop_table('sales_order_lines')
    op.drop_table('purchase_orders')
    op.drop_table('payment_milestones')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_invoices_type_date')

    op.drop_table('invoices')
    op.drop_table('supplier_offers')
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_orders_status')

    op.drop_table('sales_orders')
    with op.batch_alter_table('tax_rates', schema=None) as batch_op:
        batch_op.drop_index('ix_tax_rates_hsn_from')

    op.drop_table('tax_rates')
    op.drop_table('tally_ledger_mappings')
    op.drop_table('tally_exports')
    op.drop_table('tally_export_items')
    op.drop_table('suppliers')
    op.drop_table('items')
    op.drop_table('extractions')
    op.drop_table('documents')
    op.drop_table('document_series')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_name')

    op.drop_table('customers')
    op.drop_table('company')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
